import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import { useAppDispatch } from '../store/hooks'
import { axiosGql, getLibraryQuery } from '../services/gqlApi'
import {getLibrary} from '../store/library/librarySlice'

import styles from '../styles/Home.module.css'
import { getStore } from '../store/store'

const Home: NextPage = () => {
  const dispatch = useAppDispatch();

  useEffect(() =>{
   dispatch(getLibrary({_:"_"}))
  },[])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export async function getServerSideProps(){
  const store = getStore();
  await store.dispatch(getLibrary({_:"_"}))
  return{
    props:{
      initialState: store.getState()
    }
  }
}

export default Home
